/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "core/components/theme/theme_constants.h"

#include "core/components/base/properties/scroll_bar.h"

namespace OHOS::Ace {

ThemeConstantsMap ThemeConstants::styleMapWatch = {
    // Common
    { THEME_OHOS_COLOR_FG,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffffffff), .isPublic = true } },
    { THEME_OHOS_COLOR_BG,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff000000), .isPublic = true } },
    { THEME_OHOS_ACCENT,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff1f71ff), .isPublic = true } },
    { THEME_OHOS_FUNCTIONAL_RED,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffe62e31), .isPublic = true } },
    { THEME_OHOS_COLOR_WARNING,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffff7500), .isPublic = true } },
    { THEME_OHOS_COLOR_HANDUP,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffe62e31), .isPublic = true } },
    { THEME_OHOS_COLOR_CONNECTED,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff64bb5c), .isPublic = true } },
    { THEME_OHOS_CONTROL_NORMAL,
        { .type = ThemeConstantsType::COLOR, .value = Color(0x26ffffff), .isPublic = true } },
    { THEME_OHOS_COLOR_DIVIDER_HORIZONTAL,
        { .type = ThemeConstantsType::COLOR, .value = Color(0x33ffffff), .isPublic = true } },
    { THEME_OHOS_COLOR_SUBHEADER_DIVIDER,
        { .type = ThemeConstantsType::COLOR, .value = Color(0x26ffffff), .isPublic = true } },
    { THEME_CLICKEFFIC_DEFAULT_COLOR_OHOS,
        { .type = ThemeConstantsType::COLOR, .value = Color(0x19ffffff), .isPublic = true } },
    { THEME_OHOS_COLOR_PRIMARY,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffffffff), .isPublic = true } },
    { THEME_OHOS_COLOR_SECONDARY,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xa9ffffff), .isPublic = true } },
    { THEME_OHOS_COLOR_TERTIARY,
        { .type = ThemeConstantsType::COLOR, .value = Color(0x66ffffff), .isPublic = true } },
    { THEME_OHOS_COLOR_TEXT_PRIMARY,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffffffff), .isPublic = true } },
    { THEME_OHOS_COLOR_TEXT_SECONDARY,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xa9ffffff), .isPublic = true } },
    { THEME_OHOS_FUNCTIONAL_BLUE,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff5ea1ff), .isPublic = true } },
    { THEME_OHOS_TEXT_HINT,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xa9ffffff), .isPublic = true } },
    { THEME_OHOS_FUNCTIONAL_BLUE_INVERSE,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff5ea1ff), .isPublic = true } },
    { THEME_OHOS_COLOR_TEXT_HIGHLIGHT,
        { .type = ThemeConstantsType::COLOR, .value = Color(0x331f71ff), .isPublic = true } },
    { THEME_OHOS_COLOR_1,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff564af7), .isPublic = true } },
    { THEME_OHOS_COLOR_2,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff46b1e3), .isPublic = true } },
    { THEME_OHOS_COLOR_3,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff00b6bf), .isPublic = true } },
    { THEME_OHOS_COLOR_4,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff64bb5c), .isPublic = true } },
    { THEME_OHOS_COLOR_5,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffa5d61d), .isPublic = true } },
    { THEME_OHOS_COLOR_6,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff8a2be2), .isPublic = true } },
    { THEME_OHOS_COLOR_7,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffe02d50), .isPublic = true } },
    { THEME_OHOS_COLOR_8,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffe02d2f), .isPublic = true } },
    { THEME_OHOS_COLOR_9,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xfffb6522), .isPublic = true } },
    { THEME_OHOS_COLOR_10,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffff9800), .isPublic = true } },
    { THEME_OHOS_COLOR_11,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffffbf00), .isPublic = true } },
    { THEME_OHOS_COLOR_FG_3,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff52e4eb), .isPublic = true } },
    { THEME_OHOS_COLOR_FG_4,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff76d96c), .isPublic = true } },
    { THEME_OHOS_COLOR_FG_6,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffb566ff), .isPublic = true } },
    { THEME_OHOS_COLOR_FG_7,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffff4569), .isPublic = true } },
    { THEME_OHOS_COLOR_FG_8,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffff4d4f), .isPublic = true } },
    { THEME_OHOS_COLOR_FG_9,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffff7500), .isPublic = true } },
    { THEME_OHOS_SPECIAL_COLOR_1,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff392f49), .isPublic = true } },
    { THEME_OHOS_SPECIAL_COLOR_2,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff343e4a), .isPublic = true } },
    { THEME_OHOS_SPECIAL_COLOR_4,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff3c4b34), .isPublic = true } },
    { THEME_OHOS_SPECIAL_COLOR_7,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff443038), .isPublic = true } },
    { THEME_OHOS_SPECIAL_COLOR_9,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff463630), .isPublic = true } },
    { THEME_OHOS_SPECIAL_COLOR_11,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff4a4333), .isPublic = true } },
    { THEME_OHOS_PRIMARY_CONTENT_ALPHA,
        { .type = ThemeConstantsType::DOUBLE, .value = 1.0, .isPublic = true } },
    { THEME_OHOS_SECONDARY_CONTENT_ALPHA,
        { .type = ThemeConstantsType::DOUBLE, .value = 0.66, .isPublic = true } },
    { THEME_OHOS_TERTIARY_CONTENT_ALPHA,
        { .type = ThemeConstantsType::DOUBLE, .value = 0.4, .isPublic = true } },
    { THEME_OHOS_DISABLED_ALPHA,
        { .type = ThemeConstantsType::DOUBLE, .value = 0.4, .isPublic = true } },
    { THEME_OHOS_HIGHLIGHT_BG_ALPHA,
        { .type = ThemeConstantsType::DOUBLE, .value = 0.2, .isPublic = true } },
    { THEME_OHOS_NORMAL_BG_ALPHA,
        { .type = ThemeConstantsType::DOUBLE, .value = 0.15, .isPublic = true } },
    { THEME_OHOS_DIVIDER_ALPHA,
        { .type = ThemeConstantsType::DOUBLE, .value = 0.15, .isPublic = true } },
    { THEME_OHOS_APPBAR_TITLE,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffffffff), .isPublic = true } },
    { THEME_OHOS_APPBAR_SUBTITLE,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xa9ffffff), .isPublic = false } },
    { THEME_OHOS_COLOR_PROGRESS,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff5ea1ff), .isPublic = false } },
    { THEME_OHOS_COLOR_BADGE,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff1f71ff), .isPublic = false } },
    { THEME_OHOS_BADGE_RED,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xffe62e31), .isPublic = false } },
    { THEME_OHOS_DIALOG_BG,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff000000), .isPublic = true } },
    { THEME_OHOS_BUTTON_DEFAULT,
        { .type = ThemeConstantsType::COLOR, .value = Color(0x26ffffff), .isPublic = true } },
    { THEME_OHOS_SWITCH_BG_OFF,
        { .type = ThemeConstantsType::COLOR, .value = Color(0x33000000), .isPublic = false } },
    { THEME_OHOS_FAB_BG_NORMAL,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xff1f71ff), .isPublic = true } },
    { THEME_OHOS_FAB_BG_PRESSED,
        { .type = ThemeConstantsType::COLOR, .value = Color(0x19ffffff), .isPublic = false } },
    { THEME_OHOS_TOAST_BG,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xf2404040), .isPublic = false } },
    { THEME_OHOS_TEXT_SIZE_HEADLINE1,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(76.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_HEADLINE2,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(58.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_HEADLINE3,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(40.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_HEADLINE4,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(34.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_HEADLINE5,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(30.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_HEADLINE6,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(24.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_HEADLINE7,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(19.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_SUBTITLE1,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(19.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_SUBTITLE2,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(15.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_BUTTON1,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(19.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_BUTTON2,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(16.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_BODY1,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(19.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_BODY2,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(18.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_BODY3,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(16.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_CAPTION,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(13.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_CHART1,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(10.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_OVERLINE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(16.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_OHOS_CORNER_RADIUS_TOAST,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(20.0, DimensionUnit::DP), .isPublic = false } },
    { THEME_OHOS_CORNER_RADIUS_SWITCHBAR,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(11.0, DimensionUnit::DP), .isPublic = false } },
    { THEME_OHOS_CORNER_RADIUS_BUTTON_SMALL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(20.0, DimensionUnit::DP), .isPublic = false } },
    { THEME_OHOS_CORNER_RADIUS_CLICKED,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(4.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_CORNER_RADIUS_PROGRESSBAR,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(4.0, DimensionUnit::DP), .isPublic = false } },
    { THEME_OHOS_CORNER_RADIUS_CHECKBOX,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(4.0, DimensionUnit::DP), .isPublic = false } },
    { THEME_OHOS_CORNER_RADIUS_INPUTBOX,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(22.0, DimensionUnit::DP), .isPublic = false } },
    { THEME_OHOS_CORNER_RADIUS_XLARGE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(32.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_CORNER_RADIUS_LARGE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(24.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_CORNER_RADIUS_MEDIUMS,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(10.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_CORNER_RADIUS_SMALL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(6.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_CORNER_RADIUS_XSMAL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(2.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_DEFAULT_START,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(11.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_MAX_START,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(26.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_DEFAULT_END,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(11.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_MAX_END,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(26.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_DEFAULT_TOP,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(20.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_DEFAULT_BOTTOM_FIXED,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(36.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_DIALOG_START,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(40.0, DimensionUnit::DP), .isPublic = false } },
    { THEME_OHOS_DIMENS_DIALOG_END,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(40.0, DimensionUnit::DP), .isPublic = false } },
    { THEME_OHOS_DIMENS_DIALOG_BOTTOM,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(20.0, DimensionUnit::DP), .isPublic = false } },
    { THEME_OHOS_DIMENS_TEXT_VERTICAL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(2.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_TEXT_HORIZONTAL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(2.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_TEXT_MARGIN_PRIMARY,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(16.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_TEXT_MARGIN_SECONDARY,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(12.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_TEXT_MARGIN_TERTIARY,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(6.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_ELEMENT_VERTICAL_LARGE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(12.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_ELEMENT_VERTICAL_MIDDLE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(6.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_ELEMENT_HORIZONTAL_LARGE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(26.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_DIMENS_ELEMENT_HORIZONTAL_MIDDLE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(8.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_SPACE_SHORT,
        { .type = ThemeConstantsType::DOUBLE, .value = 1.2, .isPublic = true } },
    { THEME_OHOS_TEXT_SIZE_SPACE_LARGE,
        { .type = ThemeConstantsType::DOUBLE, .value = 1.2, .isPublic = true } },

    // App Background
    { THEME_APP_BACKGROUND, { .type = ThemeConstantsType::COLOR, .value = Color(0xff000000), .isPublic = true } },

    // Picker
    { THEME_PICKER_SHOW_BUTTONS, { .type = ThemeConstantsType::INT, .value = 0 } },
    { THEME_PICKER_BACK_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0xff000000) } },
    { THEME_PICKER_SHOW_OPTION_COUNT, { .type = ThemeConstantsType::INT, .value = 3 } },
    { THEME_PICKER_TIME_SPLITTER, { .type = ThemeConstantsType::INT, .value = 1 } },
    { THEME_PICKER_FOCUS_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0xe6ffffff) } },
    { THEME_PICKER_FOCUS_RADIUS,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(20.0, DimensionUnit::DP) } },
    { THEME_PICKER_OPTION_WIDTH, { .type = ThemeConstantsType::DOUBLE, .value = 80.0 } },
    { THEME_PICKER_SELECT_OPTION_HEIGHT, { .type = ThemeConstantsType::DOUBLE, .value = 44.0 } },
    { THEME_PICKER_NORMAL_OPTION_HEIGHT, { .type = ThemeConstantsType::DOUBLE, .value = 36.0 } },
    { THEME_PICKER_OPTION_PADDING, { .type = ThemeConstantsType::DOUBLE, .value = 8.0 } },
    { THEME_PICKER_JUMP_INTERVAL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(18.0, DimensionUnit::DP) } },
    { THEME_PICKER_COLUMN_MARGIN,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(0.0, DimensionUnit::DP) } },
    { THEME_PICKER_SELECT_OPTION_BACK_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0x00000000) } },
    { THEME_PICKER_SELECT_OPTION_RADIUS,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(20.0, DimensionUnit::DP) } },
    { THEME_PICKER_FOCUS_OPTION_BACK_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0x00000000) } },
    { THEME_PICKER_FOCUS_OPTION_RADIUS,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(20.0, DimensionUnit::DP) } },
    { THEME_PICKER_SELECT_OPTION_FONT_SIZE,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_TEXT_SIZE_HEADLINE6, .isPublic = true } },
    { THEME_PICKER_SELECT_OPTION_TEXT_COLOR,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xFF45A5FF), .isPublic = true } },
    { THEME_PICKER_FOCUS_OPTION_FONT_SIZE,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_TEXT_SIZE_HEADLINE6, .isPublic = true } },
    { THEME_PICKER_FOCUS_OPTION_TEXT_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0xFF45A5FF) } },
    { THEME_PICKER_NORMAL_OPTION_FONT_SIZE,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_TEXT_SIZE_HEADLINE7, .isPublic = true } },
    { THEME_PICKER_BUTTON_TOP_PADDING,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(16.0, DimensionUnit::DP) } },
    { THEME_PICKER_NORMAL_OPTION_FONT_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_COLOR_TEXT_SECONDARY, .isPublic = true } },
    { THEME_PICKER_SELECT_DIVIDER_THICKNESS,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(0.0, DimensionUnit::DP) } },
    { THEME_PICKER_GRADIENT_HEIGHT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(28.0, DimensionUnit::DP) } },
    { THEME_PICKER_NORMAL_OPTION_WEIGHT,
        { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(FontWeight::NORMAL) } },
    { THEME_PICKER_SELECT_OPTION_WEIGHT,
        { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(FontWeight::W500) } },
    { THEME_PICKER_FOCUS_OPTION_WEIGHT,
        { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(FontWeight::W500) } },

    // Checkbox
    { THEME_CHECKBOX_POINT_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_COLOR_FG, .isPublic = true } },
    { THEME_CHECKBOX_ACTIVE_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_ACCENT, .isPublic = true } },
    { THEME_CHECKBOX_INACTIVE_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_COLOR_SECONDARY, .isPublic = true } },
    { THEME_CHECKBOX_HOTZONE_PADDING,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(12.0, DimensionUnit::DP) } },
    { THEME_CHECKBOX_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(46.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_CHECKBOX_BORDER_RADIUS,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(4.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_CHECKBOX_BORDER_WIDTH,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(1.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_CHECKBOX_STROKE_WIDTH,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(2.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_CHECKBOX_DEFAULT_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(46.0, DimensionUnit::DP) } },
    { THEME_CHECKBOX_NEED_FOCUS, { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(false) } },
    { THEME_CHECKBOX_INACTIVE_BACKGROUND_SOLID,
        { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(true) } },

    // NavigationBar
    { THEME_NAVIGATION_BAR_LOGO_ICON_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(20.0, DimensionUnit::DP), .isPublic = true } },

    // Refresh
    { THEME_REFRESH_DEFAULT_LOADING_DISTANCE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(16.0, DimensionUnit::DP) } },
    { THEME_REFRESH_DEFAULT_PROGRESS_DISTANCE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(16.0, DimensionUnit::DP) } },
    { THEME_REFRESH_DEFAULT_REFRESHING_DISTANCE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(64.0, DimensionUnit::DP) } },
    { THEME_REFRESH_DEFAULT_MAX_DISTANCE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(120.0, DimensionUnit::DP) } },
    { THEME_REFRESH_DEFAULT_PROGRESS_DIAMETER,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(28.0, DimensionUnit::DP), .isPublic = true } },

    // Radio
    { THEME_RADIO_POINT_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_COLOR_FG, .isPublic = true } },
    { THEME_RADIO_ACTIVE_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_ACCENT, .isPublic = true } },
    { THEME_RADIO_INACTIVE_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_COLOR_SECONDARY, .isPublic = true } },
    { THEME_RADIO_HOTZONE_PADDING,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(12, DimensionUnit::DP) } },
    { THEME_RADIO_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(46.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_RADIO_BORDER_WIDTH,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(1.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_RADIO_DEFAULT_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(46.0, DimensionUnit::DP) } },
    { THEME_RADIO_INNER_SIZE_RATIO, { .type = ThemeConstantsType::DOUBLE, .value = 0.521739 } },
    { THEME_RADIO_NEED_FOCUS, { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(false) } },
    { THEME_RADIO_INACTIVE_BACKGROUND_SOLID, { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(true) } },

    // Swiper
    { THEME_SWIPER_INDICATOR_NORMAL_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_COLOR_SECONDARY, .isPublic = true } },
    { THEME_SWIPER_INDICATOR_SELECTED_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_COLOR_FG, .isPublic = true } },
    { THEME_SWIPER_INDICATOR_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(5.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_SWIPER_INDICATOR_SELECTED_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(6.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_SWIPER_INDICATOR_MASK,
        { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(true), .isPublic = true } },
    { THEME_SWIPER_INDICATOR_POINT_PADDING,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(4.0, DimensionUnit::DP) } },

    // Text
    { THEME_TEXT_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(30.0, DimensionUnit::PX), .isPublic = true } },

    // Progress
    { THEME_PROGRESS_STROKE_WIDTH, // length of each sub-scale
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(10.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_PROGRESS_SCALE_WIDTH, // thickness of each sub-scale
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(2.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_PROGRESS_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_COLOR_PROGRESS, .isPublic = true } },
    { THEME_PROGRESS_BG_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_CONTROL_NORMAL, .isPublic = true } },
    { THEME_LOADING_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0xffffffff), .isPublic = true } },
    { THEME_PROGRERSS_THICKNESS,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(4.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_PROGRESS_DEFAULT_DIAMETER,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(76.0, DimensionUnit::DP) } },
    { THEME_LOADING_PROGRESS_DEFAULT_DIAMETER,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(52.0, DimensionUnit::DP) } },
    { THEME_PROGRESS_SCALE_NUMBER, { .type = ThemeConstantsType::INT, .value = 120, .isPublic = true } },
    { THEME_SCALE_PROGRESS_DEFAULT_DIAMETER,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(750.0, DimensionUnit::PX) } },
    { THEME_PROGRESS_RING_THICKNESS,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(10.0, DimensionUnit::DP) } },
    { THEME_LOADING_PROGRESS_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0x99ffffff) } },

    // Switch
    { THEME_SWITCH_POINT_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_COLOR_FG, .isPublic = true } },
    { THEME_SWITCH_ACTIVE_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_ACCENT, .isPublic = true } },
    { THEME_SWITCH_INACTIVE_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_COLOR_TERTIARY, .isPublic = true } },
    { THEME_SWITCH_FOCUS_COLOR, { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_COLOR_FG } },
    { THEME_SWITCH_INACTIVE_BACKGROUND_SOLID,
        { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(true) } },
    { THEME_SWITCH_BORDER_WIDTH,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(1.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_SWITCH_WIDTH,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(46.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_SWITCH_HEIGHT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(46.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_SWITCH_DEFAULT_WIDTH,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(46.0, DimensionUnit::DP) } },
    { THEME_SWITCH_DEFAULT_HEIGHT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(46.0, DimensionUnit::DP) } },
    { THEME_SWITCH_HOTZONE_HORIZONTAL_PADDING,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(7.0, DimensionUnit::DP) } },
    { THEME_SWITCH_HOTZONE_VERTICAL_PADDING,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(11.5, DimensionUnit::DP) } },
    { THEME_SWITCH_ASPECT_RATIO, { .type = ThemeConstantsType::DOUBLE, .value = 1.3913 } },
    { THEME_SWITCH_NEED_FOCUS, { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(false) } },

    // List
    { THEME_LIST_DIVIDER_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0x33FFFFFF) } },

    // List Item
    { THEME_ITEM_CLICK_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0xffffffff) } },
    { THEME_ITEM_CLICK_ALPHA_BEGIN, { .type = ThemeConstantsType::DOUBLE, .value = 0.0 } },
    { THEME_ITEM_CLICK_ALPHA_END, { .type = ThemeConstantsType::DOUBLE, .value = 0.1 } },
    { THEME_ITEM_CLICK_SCALE, { .type = ThemeConstantsType::DOUBLE, .value = 0.95 } },
    { THEME_ITEM_FOCUS_SCALE, { .type = ThemeConstantsType::DOUBLE, .value = 1.12 } },
    { THEME_ITEM_FOCUS_SCALE_LARGE, { .type = ThemeConstantsType::DOUBLE, .value = 0.94 } },
    { THEME_ITEM_FOCUS_SCALE_MIDDLE, { .type = ThemeConstantsType::DOUBLE, .value = 0.8 } },
    { THEME_ITEM_FOCUS_SCALE_LITTLE, { .type = ThemeConstantsType::DOUBLE, .value = 0.6 } },
    { THEME_ITEM_FOCUS_OPACITY_LARGE, { .type = ThemeConstantsType::DOUBLE, .value = 1.0 } },
    { THEME_ITEM_FOCUS_OPACITY_MIDDLE, { .type = ThemeConstantsType::DOUBLE, .value = 0.66 } },
    { THEME_ITEM_FOCUS_OPACITY_LITTLE, { .type = ThemeConstantsType::DOUBLE, .value = 0.38 } },
    { THEME_ITEM_FOCUS_ANIMATION_DURATION, { .type = ThemeConstantsType::DOUBLE, .value = 100.0 } },
    { THEME_ITEM_CLICK_ANIMATION_DURATION, { .type = ThemeConstantsType::DOUBLE, .value = 200.0 } },
    { THEME_ITEM_SIZE, { .type = ThemeConstantsType::DIMENTION, .value = Dimension(76.0, DimensionUnit::DP) } },
    { THEME_ITEM_MARGIN_IN_PERCENT, { .type = ThemeConstantsType::DOUBLE, .value = 0.0 } },
    { THEME_ITEM_GROUP_IMAGE_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(28.0, DimensionUnit::DP) } },

    // Dialog
    { THEME_DIALOG_CONTENT_TEXT_FONTSIZE,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_TEXT_SIZE_HEADLINE7, .isPublic = true } },
    { THEME_DIALOG_CONTENT_TEXT_FONTSIZE_MIN,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(18.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_DIALOG_PADDING_MIN, { .type = ThemeConstantsType::DIMENTION, .value = Dimension(4.0, DimensionUnit::DP) } },
    { THEME_DIALOG_PADDING_MID, { .type = ThemeConstantsType::DIMENTION, .value = Dimension(8.0, DimensionUnit::DP) } },
    { THEME_DIALOG_PADDING_MAX,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(24.0, DimensionUnit::DP) } },
    { THEME_DIALOG_BUTTON_SPACING_HORIZONTAL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(8.0, DimensionUnit::DP) } },
    { THEME_DIALOG_PADDING_LEFT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(40.0, DimensionUnit::DP) } },
    { THEME_DIALOG_PADDING_TOP,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(12.0, DimensionUnit::DP) } },
    { THEME_DIALOG_PADDING_RIGHT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(40.0, DimensionUnit::DP) } },
    { THEME_DIALOG_PADDING_BOTTOM,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(20.0, DimensionUnit::DP) } },
    { THEME_DIALOG_PADDING_LEFT_ADJUST,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(26.0, DimensionUnit::DP) } },
    { THEME_DIALOG_PADDING_TOP_ADJUST,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(40.0, DimensionUnit::DP) } },
    { THEME_DIALOG_PADDING_RIGHT_ADJUST,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(26.0, DimensionUnit::DP) } },
    { THEME_DIALOG_PADDING_BOTTOM_ADJUST,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(0.0, DimensionUnit::DP) } },
    { THEME_DIALOG_TITLE_PADDING_VERTICAL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(24.0, DimensionUnit::DP) } },
    { THEME_DIALOG_SCALE_START, { .type = ThemeConstantsType::DOUBLE, .value = 1.2 } },
    { THEME_DIALOG_MASK_COLOR_END, { .type = ThemeConstantsType::COLOR, .value = Color(0xff000000) } },
    { THEME_DIALOG_ANIMATION_DURATION_IN, { .type = ThemeConstantsType::INT, .value = 300, .isPublic = true } },
    { THEME_DIALOG_ANIMATION_DURATION_OUT, { .type = ThemeConstantsType::INT, .value = 250, .isPublic = true } },
    { THEME_DIALOG_BUTTON_BG_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0xff007dff) } },
    { THEME_DIALOG_BUTTON_CLICKED_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0xff1989ff) } },

    // Button
    { THEME_BUTTON_HEIGHT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(40.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_BUTTON_MIN_WIDTH,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(116.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_BUTTON_RADIUS,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(20.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_BUTTON_BACKGROUND_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_CONTROL_NORMAL, .isPublic = true } },
    { THEME_BUTTON_CLICKED_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0xff3b3b3b) } },
    { THEME_BUTTON_DISABLED_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_CONTROL_NORMAL, .isPublic = true } },
    { THEME_BUTTON_DISABLED_ALPHA, { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_DISABLED_ALPHA } },
    { THEME_BUTTON_TEXT_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_FUNCTIONAL_BLUE, .isPublic = true } },
    { THEME_BUTTON_TEXT_DISABLED_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_FUNCTIONAL_BLUE,
          .blendAlpha = 0.38, .isPublic = true } },
    { THEME_BUTTON_TEXT_FONTSIZE,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_TEXT_SIZE_BUTTON2, .isPublic = true } },
    { THEME_BUTTON_TEXT_FONTSIZE_MIN,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(13.0, DimensionUnit::SP), .isPublic = true } },
    { THEME_BUTTON_TEXT_FONTWEIGHT,
        { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(FontWeight::W500), .isPublic = true } },
    { THEME_BUTTON_PADDING_HORIZONTAL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(16.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_BUTTON_PROGRESS_COLOR, { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_COLOR_PROGRESS } },
    { THEME_BUTTON_PROGRESS_DIAMETER,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(38.0, DimensionUnit::DP) } },
    { THEME_BUTTON_CIRCLE_MIN_DIAMETER,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(52.0, DimensionUnit::DP) } },
    { THEME_BUTTON_CIRCLE_MIN_ICON_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(28.0, DimensionUnit::DP) } },
    { THEME_BUTTON_CIRCLE_MIN_PADDING,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(12.0, DimensionUnit::DP) } },
    { THEME_BUTTON_CIRCLE_MAX_DIAMETER,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(76.0, DimensionUnit::DP) } },
    { THEME_BUTTON_CIRCLE_MAX_ICON_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(38.0, DimensionUnit::DP) } },
    { THEME_BUTTON_CIRCLE_MAX_PADDING,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(19.0, DimensionUnit::DP) } },

    // scrollBar
    { THEME_SCROLL_BAR_NORMAL_WIDTH,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(3.0, DimensionUnit::DP) } },
    { THEME_SCROLL_BAR_ACTIVE_WIDTH,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(6.0, DimensionUnit::DP) } },
    { THEME_SCROLL_BAR_MIN_HEIGHT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(48.0, DimensionUnit::DP) } },
    { THEME_SCROLL_BAR_MIN_DYNAMIC_HEIGHT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(3.0, DimensionUnit::DP) } },
    { THEME_SCROLL_BAR_RESERVED_HEIGHT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(0.0, DimensionUnit::DP) } },
    { THEME_SCROLL_BAR_TOUCH_WIDTH,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(32.0, DimensionUnit::DP) } },
    { THEME_SCROLL_BAR_BACKGROUND_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_CONTROL_NORMAL, .isPublic = true } },
    { THEME_SCROLL_BAR_FOREGROUND_COLOR, { .type = ThemeConstantsType::REFERENCE,
                                             .value = THEME_OHOS_COLOR_PRIMARY,
                                             .blendAlpha = THEME_OHOS_SECONDARY_CONTENT_ALPHA,
                                             .isPublic = true } },
    { THEME_SCROLL_BAR_SHAPE_MODE,
        { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(ShapeMode::ROUND) } },
    { THEME_SCROLL_BAR_PADDING_RIGHT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(0.0, DimensionUnit::DP) } },

    // Toast
    { THEME_TOAST_PADDING_HORIZONTAL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(16.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_TOAST_PADDING_VERTICAL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(10.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_TOAST_CONTENT_MIN_WIDTH,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(116.0, DimensionUnit::DP) } },
    { THEME_TOAST_CONTENT_MIN_HEIGHT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(40.0, DimensionUnit::DP) } },
    { THEME_TOAST_BACKGROUND_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_TOAST_BG, .isPublic = true } },
    { THEME_TOAST_TEXT_TEXT_FONTWEIGHT,
        { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(FontWeight::NORMAL), .isPublic = true } },
    { THEME_TOAST_TEXT_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_COLOR_TEXT_PRIMARY, .isPublic = true } },
    { THEME_TOAST_TEXT_FONTSIZE,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_TEXT_SIZE_BODY3, .isPublic = true } },
    { THEME_TOAST_RADIUS,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(20.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_TOAST_TEXT_FONTSIZE_MIN,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(13.0, DimensionUnit::SP) } },
    { THEME_TOAST_TEXT_MAX_LINES, { .type = ThemeConstantsType::INT, .value = 2 } },
    { THEME_TOAST_MARGIN, { .type = ThemeConstantsType::DIMENTION, .value = Dimension(14.0, DimensionUnit::DP) } },

    // Slider
    { THEME_SLIDER_TRACK_BG,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_CONTROL_NORMAL, .isPublic = true } },
    { THEME_SLIDER_TRACK_SELECTED,
      { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_ACCENT, .isPublic = true } },

    // divider
    { THEME_DIVIDER_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0x33FFFFFF) } },

    // TextField
    { THEME_TEXTFIELD_PADDING_HORIZONTAL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(24.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_TEXTFIELD_PADDING_VERTICAL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(12.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_TEXTFIELD_HEIGHT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(48.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_TEXTFIELD_FONT_SIZE,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_TEXT_SIZE_BODY1, .isPublic = true } },
    { THEME_TEXTFIELD_FONT_WEIGHT,
        { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(FontWeight::W500), .isPublic = true } },
    { THEME_TEXTFIELD_BORDER_RADIUS,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(20.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_TEXTFIELD_NEED_FADE, { .type = ThemeConstantsType::INT, .value = 1 } },
    { THEME_TEXTFIELD_BACKGROUND_COLOR,
        { .type = ThemeConstantsType::COLOR, .value = Color(0x33FFFFFF), .isPublic = true } },
    { THEME_TEXTFIELD_TEXT_COLOR, { .type = ThemeConstantsType::COLOR, .value = Color(0xE6FFFFFF), .isPublic = true } },
    { THEME_TEXTFIELD_FOCUS_BACKGROUND_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_CONTROL_FOCUSED, .isPublic = true } },
    { THEME_TEXTFIELD_FOCUS_TEXT_COLOR,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xE6FFFFFF), .isPublic = true } },
    { THEME_TEXTFIELD_OVER_HIDE_LENGTH,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(24.0, DimensionUnit::DP) } },
    { THEME_TEXTFIELD_CURSOR_COLOR,
        { .type = ThemeConstantsType::COLOR, .value = Color(0xFF254FF7), .isPublic = true } },
    { THEME_TEXTFIELD_CURSOR_RADIUS,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(1.0, DimensionUnit::DP) } },
    { THEME_TEXTFIELD_SHOW_ELLIPSIS, { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(false) } },
    { THEME_TEXTFIELD_ERROR_SPACING,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(24.0, DimensionUnit::DP) } },
    { THEME_TEXTFIELD_ERROR_IS_INNER, { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(true) } },
    { THEME_TEXTFIELD_ERROR_BORDER_WIDTH,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(1.0, DimensionUnit::DP) } },

    // search
    { THEME_SEARCH_ICON_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(16.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_SEARCH_ICON_HOT_ZONE_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(32.0, DimensionUnit::DP) } },
    { THEME_SEARCH_TEXT_FIELD_PADDING_LEFT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(24.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_SEARCH_TEXT_FIELD_BORDER_RADIUS,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_CORNER_RADIUS_INPUTBOX, .isPublic = true } },
    { THEME_SEARCH_TEXT_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_TEXT_HINT_INVERSE, .isPublic = true } },
    { THEME_SEARCH_PLACEHOLDER_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_TEXT_HINT, .isPublic = true } },
    { THEME_SEARCH_CLOSE_ICON_SIZE,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(16.0, DimensionUnit::DP), .isPublic = true } },
    { THEME_SEARCH_CLOSE_ICON_HOT_ZONE_HORIZONTAL,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(40.0, DimensionUnit::DP) } },
    { THEME_SEARCH_DEFAULT_HEIGHT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(48.0, DimensionUnit::DP) } },
    { THEME_SEARCH_FONT_SIZE,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_TEXT_SIZE_BODY1, .isPublic = true } },
    { THEME_SEARCH_FONT_WEIGHT,
        { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(FontWeight::W500), .isPublic = true } },
    { THEME_SEARCH_TEXT_FIELD_PADDING_RIGHT,
        { .type = ThemeConstantsType::DIMENTION, .value = Dimension(24.0, DimensionUnit::DP) } },
    { THEME_SEARCH_FOCUS_TEXT_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_TEXT_HINT_INVERSE, .isPublic = true } },
    { THEME_SEARCH_BLOCK_RIGHT_SHADE, { .type = ThemeConstantsType::INT, .value = static_cast<int32_t>(true) } },
    { THEME_SEARCH_FOCUS_PLACEHOLDER_COLOR,
        { .type = ThemeConstantsType::REFERENCE, .value = THEME_OHOS_TEXT_HINT_INVERSE } },
};

} // namespace OHOS::Ace
